### ISSUE TITLE
Dynamic radio buttons

### ISSUE THREAD

**Issue by AKMohite** [mrHerintsoaHasina/flextools#2]
Unable to have single radio button checked when added programatically.
![Screenshot_20200115-165844](https://user-images.githubusercontent.com/18052898/72430500-8c905200-37b8-11ea-9188-b689ad0c320d.png)

**Comment by mrHerintsoaHasina** [comment]
Can you write here your code on how you use it programatically ?

**Comment by AKMohite** [comment]
I have solved it by setting ids of radio buttons programatically.
